### ISSUE TITLE
Some Samples Don't work

### ISSUE THREAD

**Issue by dmitriyyepishin** [OfficeDev/Office-UI-Fabric#114]
Some samples I tried (in dist/samples) reference JS code that does not exist. For example dist\samples\Components\Table\index.html has a reference to Jquery.Table.js, Table.js: both of which do not exist. Same for Breadcrumb sample. Those are the ones I tried, but maybe there are others.

**Comment by Jahnp** [comment]
Thanks! This is actually a known issue: https://github.com/OfficeDev/Office-UI-Fabric/issues/67 . We're working on a fix for it now.

Basically, the template used for component demo HTML pages has a hard-coded reference to `<Component>.js` and `Jquery.<Component>.js`, even if those files don't exist. Since several components, like the ones you mentioned and a few others, do not require JavaScript to function, those files don't exist--hence the errors. 

The fix for this should be ready soon, and will be available in our next release. I'll close this issue for now since the work for it is already being tracked, unless I'm missing something. Thanks for catching this!
