### ISSUE TITLE
Library needs Typescipt Definitions

### ISSUE THREAD

**Issue by brijeshb** [OfficeDev/Office-UI-Fabric#121]
Would make the widgets a lot more useful if they had some typescript definition files.

**Comment by Jahnp** [comment]
Yep, this makes lots of sense, and will be a given as we dig deeper into JS support for components. I would expect to see TypeScript as an essential part of our longer-term JS story, especially as we extend into support for other frameworks & libraries. 

Though, to be honest, the jQuery plugins have been demonstration-only and not necessarily production-ready--not to say that shouldn't change at some point--but because of that, I'm not sure definitions would be immediately useful. Would you still want d.ts files for those as well?

**Comment by oising** [comment]
TypeScript definitions for All the Things (tm)

**Comment by ericthompson** [comment]
![image](https://cloud.githubusercontent.com/assets/1420854/11017103/86cc4ff2-8549-11e5-9d47-a75a3905ecc5.png)
(tm)

**Comment by mikewheaton** [comment]
This is now on [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/issues/122). We'll be replacing the jQuery plugins with TypeScript for each component.

**Comment by oising** [comment]
@mikewheaton Great news!

**Comment by ericthompson** [comment]
:+1:

**Comment by sqlsolver** [comment]
Soon?
