### ISSUE TITLE
Update changelog for 1.1.0

### ISSUE THREAD

**Issue by pascalberger** [OfficeDev/Office-UI-Fabric#158]
It seems like https://github.com/OfficeDev/Office-UI-Fabric/blob/master/CHANGELOG.md isn't updated with the changes of the 1.1.0 release.

**Comment by Jahnp** [comment]
Great catch! I've added the release notes from the [1.1.0 release](https://github.com/OfficeDev/Office-UI-Fabric/release/tag/1.1.0). We'll likely transition to solely using GitHub releases for changelog management, but in the meantime we'll keep both since there links pointing to the changelog elsewhere. Thanks! I'll close for now.
