### ISSUE TITLE
Update table markup

### ISSUE THREAD

**Issue by cbarnes01** [OfficeDev/Office-UI-Fabric#192]
How do you accomplish column spans with the table component?

**Comment by jigargandhi** [comment]
+1

**Comment by StfBauer** [comment]
The table implementation is in general not recommended. You can use the same css classes and assign it to the table related HTML Elements.
Column span can only be applied directly on td and th elements but there is no equivalent to columns span available in CSS.
This will never work with the current implementation.

**Comment by mikewheaton** [comment]
Our [table component](http://dev.office.com/fabric/components/table) was originally built for use in a scenario where the layout had to change completely on smaller screen sizes. This resulted in the use of `div`s rather than a standard `table` element.

We should revisit this decision, as using `table` would simplify the HTML and allow it to behave as you'd expect -- such as by respecting the `colspan` and `rowspan` attributes.

**Comment by StfBauer** [comment]
The same effect could be achieved with tables too because they are only effected by the display properties:
table ..... display: table
tr ........... display: table-row
td .......... display: table-cell

Those properties can always be changed to other display behaviors like block, inline-block, inline and so on. While there was a lack on browser support on older browser using div based table looked like to be good an alternative to tables.
Alternatively a table can always be embedded in a div element that allows scrolling through overflow.
The benefit is that the data kept together but doesn't break the mobile design.

**Comment by mikewheaton** [comment]
Over in #276, @StfBauer demonstrates that our current classes can be used with a standard `table` structure.

@cbarnes01: You should be able to replace the `div`s in your current implementation with `table`, `td`, `tr`, etc. and then use the [colspan attribute](http://www.w3schools.com/tags/att_td_colspan.asp) to get the result you're looking for.

**Comment by StfBauer** [comment]
@mikewheaton From my side a blog post concerning this issue is coming up tomorrow. How responsive pattern can be applied to the table or at least in general how you can deal with table it in responsive scenarios.

**Comment by StfBauer** [comment]
@mikewheaton Spotted and documented some issues and maybe improvements.

**Comment by mikewheaton** [comment]
Excellent blog post, @StfBauer! We'll be using it as a reference as we update the reference HTML and consider responsive behaviors.

**Comment by mikewheaton** [comment]
Okay, we're going to go ahead and change the markup from `div`s to a `table` element. I've opened a [new issue](https://github.com/OfficeDev/Office-UI-Fabric/issues/292) to get design input on making tables responsive.
