### ISSUE TITLE
No Components RTL LESS file

### ISSUE THREAD

**Issue by Steve887** [OfficeDev/Office-UI-Fabric#210]
There doesn't appear to be a RTL LESS file for components in the src/less directory, nor is there RTL less files for each component. I note in the gulp file that while it less-ifies the left-to-right fabric files, it simply minifies and copies an existing fabric.components.rtl.css file.

Is this a known issue, and/or is there a LESS file for right-to-left components?

**Comment by Jahnp** [comment]
This is correct. There is no need for separate RTL versions of either Fabric.Components.less or individual component LESS file, since the build step handles *all* the necessary RTL conversions for Components. 

By contrast, core bits like icons and animations need to be manually flipped with separate RTL files, since:

1. Not every icon or animation needs to be flipped for RTL, and 
2. The techniques for these modules can differ from what the build tool will automate. For example, RTL icons are flipped using `transform: scaleX(-1)`, which effectively "mirrors" them across the x-axis. 

This is why we have separate RTL files for those modules, and why we don't need them for, say, the Grid, which is also flipped automatically, like the components.

Does that help? Is there a reason you'd like an RTL LESS file for components? I want to make sure we're not missing a useful scenario here. Thanks!

**Comment by Steve887** [comment]
The scenario I'm in is I am adding the main LESS files as imports in my site's LESS file so I can put my custom styles and Fabric styles together allowing me to access the classes defined in Fabric in my custom styles and to end up with one minified CSS file.

**Comment by ericthompson** [comment]
Ah, I see. The way that our RTL styles work right now is that they're separate files that can be swapped out depending on what's needed - they shouldn't be used at the same time. However, we recognize the need for combining them into one file, and we'll put it on our backlog. No ETA, unfortunately, but we can loop back when we have an update.

**Comment by mikewheaton** [comment]
The goal here is to have both the LTR and RTL styles loaded on the same page without conflicting, right I'm thinking we'd just nest _all_ of the RTL styles within a selector like `*[dir="rtl"]` so that they would only apply to RTL pages or regions. Hopefully that extra selector would add enough specificity to override the LTR styles.

@Steve887: If you're still working on this, could you try the suggestion above and let us know how it goes?

**Comment by Steve887** [comment]
I'm not working on this, we've moved in a different direction.

**Comment by mikewheaton** [comment]
I've added this to [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md) as something we might pursue in the future if we see interest from more people.
