### ISSUE TITLE
Consider creating an example on how to integrate fabric people picker styling 

### ISSUE THREAD

**Issue by oising** [OfficeDev/Office-UI-Fabric#227]
It's not at all obvious (to me) how to apply the people picker styling to the OOTB sharepoint online / 2013 people picker. Could one of your team blog or post a "how to" article? It's beyond my patience to figure it out (and given the general frustration with the people picker, I'd imagine its beyond many peoples' patience.)

Great work nonetheless.

**Comment by ericthompson** [comment]
Hi @oising,

Have you seen [this People Control](https://github.com/OfficeDev/Office-365-People-Controls)? These are official JavaScript Office Controls that come pre-skinned with Fabric. I can reference you to one of my colleagues, @zholi, who may also be able to help. I know this isn't exactly the OOTB SPO/2013 People Picker, but it might be a good start.

Let me know if this is at all helpful - if not, I'll go on ahead and ping other folks who may be able to assist you.

Cheers!

**Comment by oising** [comment]
I guess I should be more specific. I see there are many external people picker controls out there, designed to be used on provider-hosted or independent sites. They are not the problem - SharePoint hosted integration is the issue at hand. The former is easy because you're building from scratch and have full control; when going SharePoint hosted, it's all tied up with the spaghetti mess of interdependent, incomprehensible scripts that ship with the product, with a hearty dose of "minimal download strategy" and "scripts on demand" layered on top.

**Comment by ericthompson** [comment]
Gotcha and I can totally understand your frustration.

Currently, Fabric *can* be used with SharePoint, but it's not something that's deeply supported for the existing UX (see [here](https://msdn.microsoft.com/en-us/library/office/jj220046.aspx#Fabric) for the more official statement). As things progress on our side, you can expect for it to be a lot easier to style the OOTB SP People Picker.

In order to get you help though, I would definitely recommend that you check out [the Office Dev Center User Voice site](http://officespdev.uservoice.com/) and file an ask there. I'm sure other folks are facing your same dilemma, and this is the best place to get your question posed to the right folks.

**Comment by oising** [comment]
Thanks @ericthompson
