### ISSUE TITLE
Document the .ms-fontSize-[size] classes

### ISSUE THREAD

**Issue by TheTedAdams** [OfficeDev/Office-UI-Fabric#275]
## Edit for clarity:
the `ms-fontSize-[size]` classes are not currently documented on the [styles documentation page](http://dev.office.com/fabric/styles). They should be added to the styles documentation.

## Original issue text:
For discussion, I think that `color` should not be declared in the `.ms-font-*` classes.

Anywhere I want the color to be `@ms-color-neutralPrimary` I can probably inherit from the parent, and redeclaring it on any element where I try to use `.ms-font-*` to change text size makes these classes difficult to use on any background other than white.

As these classes seem to be intended as font size modifiers, changes in `font-size` and `font-weight` (In this case achieved by using a differently weighted `font-family`) make good sense, but declaring `color` seems to over-reach what I see as the usefulness of the classes, and in fact there are specifically other classes to handle `color`.

Curious to hear any reasons why these classes should continue to declare `color`.

**Comment by mikewheaton** [comment]
Thanks for reaching out, @TheTedAdams. The `.ms-font-[size]` classes are intended as base font classes, and they intentionally set the size, weight, and color. You can apply these classes to a single text element, or on a container for inheritance down to all of the text inside.

To change the size of a specific element (independent of color and weight) we provide `ms-fontSize-[size]` classes. You may not have known about these because they're missing from our [styles documentation page](http://dev.office.com/fabric/styles). Sorry about that. With classes for size, color, and weight it's possible to apply all of the text properties without ever using a base class.

Now that you know about these classes (e.g. `ms-fontSize-xl`) do they fit your needs? Here's an example of how you could combine the base classes and a size override:

```
<div class="ms-font-m">
  <p>This paragraph will inherit the medium font size set by the base class.</p>
  <p>And so will this paragraph.</p>
  <p class="ms-font-xl">This paragraph has a size class that makes it larger.</p>
</div>
```
**[Demonstration on CodePen](http://codepen.io/mikewheaton/pen/mVBKeG)**

**Comment by mikewheaton** [comment]
Leaving this issue open so that we can get the `.ms-fontSize-[size]` classes documented.

**Comment by TheTedAdams** [comment]
That will work. I still think it would be useful to be able to declare size and weight with a single class (since that is how the typography will normally be scaled) without color, but for now I can do it with `ms-fontSize-*` and `ms-fontWeight-*`. Thanks for the info!

**Comment by TheTedAdams** [comment]
Are the `.ms-fontSize-[size]` classes going to be in the documentation? Issue closed and I don't see them at http://dev.office.com/fabric/styles

**Comment by mikewheaton** [comment]
My mistake, we should definitely keep this issue open until we've documented the size classes.

**Comment by mikewheaton** [comment]
Created a pull request on our internal documentation repo that documents the `.ms-fontSize-[size]` classes.

While we understand that some users of Fabric (like @TheTedAdams) would prefer that the base classes not include color, this is an important part of the design language and something that we want to keep in place. The documentation updates will make this clear to prevent confusion.
