### ISSUE TITLE
Datepicker does not work with pickadate @ 3.5.6

### ISSUE THREAD

**Issue by rolandoldengarm** [OfficeDev/Office-UI-Fabric#336]
When using latest pickadate.js (@3.5.6) there is an issue with the z-index:

[Plunkr 3.5.3 (works)](http://plnkr.co/edit/1nvSwsFmYVHj7ZYjEnBW?p=preview)
[Plunkr 3.5.6 (z-index issue)](http://plnkr.co/edit/IQGG16airKNuWHiUVoIA?p=preview)
Just click on the first datepicker.

This is caused by the --focus class not being applied, so it seems a bug in pickadate.js.
As you are including a custom pickadate.js version, I haven't raised this (yet) with pickadate.js.

**Comment by mikewheaton** [comment]
Thanks for reporting this. You're right that it's caused by the `.ms-DatePicker-picker--focused` class not being applied in the latest version of Pickadate. For this bug we can actually just update our styles to target only the `.ms-DatePicker-picker--opened` class. I'll submit a pull request for this.
