### ISSUE TITLE
License update for SP add-ins and Office 365 applications

### ISSUE THREAD

**Issue by VesaJuvonen** [OfficeDev/Office-UI-Fabric#341]
Fabric has following in the license: Usage of the fonts referenced on Office UI Fabric files is subject to the terms listed at http://aka.ms/fabric-font-license

This refers to following location: http://appsforoffice.microsoft.com/fabric/Segoe_UI_and_Fabric_CDN_License.txt, which defines as follows: "You may install and use any number of copies of the fonts and/or Fabric Assets on your devices solely for the purpose of developing UI for Office Add-Ins.".

This would imply that the material cannot be used with SP add-ins or Office 365 applications, which is causing questions from the community. In general Fabric uses MIT license, but community members are reading above and would not like to break the rules defined by Microsoft, which is now causing confusion and doubts on usage policies.

**Comment by ericthompson** [comment]
Hi @VesaJuvonen - all Fabric assets distributed via GitHub are licensed under the MIT license which means you can use them on any projects provided you follow the MIT license. Specifically for the fonts, as stated by their license, you can use them only on Office Add-Ins. In this context Office Add-Ins include any web applications that extend the Office User Experience including: Office Add-Ins (previously known as Apps for Office), SharePoint Add-Ins (previously known as Apps for SharePoint) and Office 365 Apps (those launched from within the Office launcher).

All of this in mind, I'm going to reach out to contacts on my side to see if we can change the wording here to make it less confusing. Leaving open for now as I dig in!

**Comment by StfBauer** [comment]
The current state indeed is pretty confusing, I asked a similar question to this previously in issue #216 .

[MIT License](https://opensource.org/licenses/MIT) says that I can do whatever I like to do with Office UI Fabric as long as I include the MIT License and mention it is built upon Office UI Fabric. That is what GITHub says and then you have other license information like the one @VesaJuvonen mentioned.

When you take a look at the license statement here on Github for example it say first "All rights reserved" which basically means "Don't touch it" but then you have the MIT License terms. Which basically say do whatever you want with Office UI Fabric as long as you mention Office UI Fabric. You are event allowed to sell software based on Office UI Fabric and can use a different license than MIT.
This leads to a license information conflict because "No rights reserved" and "All rights reserved" won't match together.

Web fonts are always a problem. Segeo UI font is copyright protected which means you cannot use it under MIT License and you are definitly not allowed to distribute it as a web fonts together with Office UI Fabric.
Similar issue exists with the icon font included in the Office UI Fabric or Office 365. This font is basically not part of Segeo UI font. I guess this font is copyright protected too but never found an copyright notice on that. Actually someone at Microsoft used a tool named [icomoon](https://icomoon.io/app/) to generate a web font out of those icons.
What will I do if I like create a node.js application that might run on a client and use the same look and feel as Office for convenience. In this case I might not be able to use Office UI Fabric. It's no problem for Windows user because they have the fonts installed but I won't be able to create cross platform applications that way or use a different font.

@ericthompson Would be great if the same licenses will be used in all available source. Looking up what information you got. Thank you for your effort.

**Comment by ericthompson** [comment]
OK! So I apologize for it being a little while, but legal matters can sometimes be confusing and take time for me to iron out.

I've worked with legal on our side to get [the license](http://appsforoffice.microsoft.com/fabric/Segoe_UI_and_Fabric_CDN_License.txt) that goes alongside the fonts (icons and Segoe UI) to better reflect the intended usage of those assets: extending the Office/Office 365 User Experience. It also more clearly calls out that the CSS is not the intended "target" of the license for the fonts.

The fonts included with Fabric (that are up on the CDN) are a part of the Segoe UI family and are, therefore, covered by the above linked license. My hope is that the newly updated license helps make it clearer that you can use it for the purposes @VesaJuvonen asked about.

The MIT License, on the other hand, covers the *code* in the repository and does not include the fonts (Segoe UI and iconography). The two licenses are quite different, and I hope the wording changes prevent confusion about their possible overlap.

I hope this helps!
