### ISSUE TITLE
Use SVG for icons

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/Office-UI-Fabric#378]
With [GitHub's recent change to SVGs](https://github.com/blog/2112-delivering-octicons-with-svg) we've been discussing replacing the icon font with a collection of SVGs. This has the potential to make bundling simpler, by not requiring a subset of the font to select which assets are delivered to the browser, that could improve performance. There are also accessibility benefits.

One thing we’d want to figure out for Fabric is how to include the icons with CSS only. For example, if you look at the notifications bell in GitHub it has this markup:
 
```
<svg aria-hidden="true" class="octicon octicon-bell" height="16" role="img" version="1.1" viewBox="0 0 14 16" width="14">
  <path d="M14 12v1H0v-1l0.73-0.58c0.77-0.77 0.81-2.55 1.19-4.42 0.77-3.77 4.08-5 4.08-5 0-0.55 0.45-1 1-1s1 0.45 1 1c0 0 3.39 1.23 4.16 5 0.38 1.88 0.42 3.66 1.19 4.42l0.66 0.58z m-7 4c1.11 0 2-0.89 2-2H5c0 1.11 0.89 2 2 2z"></path>
</svg>
```
 
They’re injecting the paths directly into the page source on the server, so when an icon is updated all of the instances reflect that. For Fabric we want to do everything on the front end, ideally without JavaScript.

We'd love some ideas from the community on this.

**Comment by manndave** [comment]
I am by no means an expert on CSS and SVGs, but so long as

1. We can still style the icons (color, size, background) solely with CSS
2. We don't take on a server-side dependency

it seems to make sense.  My questions would be...what would we lose and what gets harder?

Also, would the perf improvement be initial load only, and after that the fonts are cached locally?  If so, that negates a lot of the perf benefits, IMHO.

**Comment by constancecchen** [comment]
I recently switched from FontAwesome to a external SVG file/"spritesheet" with symbols, and it wasn't as bad as I thought it'd be. Admittedly, this was for a small personal site, and not for a large framework :)

What I really dig most is the ability to quickly add/remove icons (can be as simple as opening up the SVG file in an editor and deleting/adding a symbol). It just feels cleaner and more minimal than an icon font, which may potentially have tons of icons that aren't being used. In terms of support and fallback, I use a polyfill called svgxuse that makes links/references to external SVG files work on IE, and it works with very little hassle.

The markup can be just as minimal as icon fonts as well. Compare:
`<svg><use xlink:href="/icons.svg#icon-facebook"></use></svg>`
to:
`<i class="fa fa-facebook"></i>`
Although normally you'll probably add a class to the svg tag, as well as adding an inline text fallback for browsers that don't support SVG (IE8, Android 2.3, etc.).

Here's the main tutorial/blog post that I used as a guide throughout the process - it was incredibly useful and well worth the read. It also has a ton of extra useful info, such as using gulp to concatenate/minify your final SVG spritesheet, accessibility, and so forth. http://blog.cloudfour.com/our-svg-icon-process/

And here's a broader resource/blog post that may be useful as well: https://24ways.org/2014/an-overview-of-svg-sprite-creation-techniques/

**Comment by StfBauer** [comment]
@mikewheaton I converted the Office Icon font a couple of month ago to a svg symbol set. I can add it if needed.
Browser support is not a big issue anymore as seen in: [http://caniuse.com/#search=svg](http://caniuse.com/#search=svg)
Actually to use icon fonts is really bad practice these days and propramatical especially in matter of usabiliy.

This was actually the reason my I switch to svg rather than use an icon font.
Reason Number One was this article: [Seriously don't use icon fonts](http://blog.cloudfour.com/seriously-dont-use-icon-fonts/)
Reason Number Two was this video: [Seren Davies: Death to icon fonts](https://www.youtube.com/watch?v=9xXBYcWgCHA)

**Comment by mikewheaton** [comment]
@StfBauer: So you have a set of files, with one icon per SVG? How do you use an SVG on the page? It seems clear that [SVG has many advantages](https://css-tricks.com/icon-fonts-vs-svg/), we just want to also:
- Make it simple to use an icon (`.ms-Icon--mail` class and it magically appears)
- Allow for subsetting of the full icon set (a custom sprite?) to reduce download time...
- ... *or* make each icon a separate file, at the risk of having many HTTP requests slowing it down
- Have the icon inherit the parent's color, or make it easy to apply a custom color through a CSS class

**Comment by StfBauer** [comment]
**Make it simple to use an icon**
That one is easy simply define:
```
.icon{
	display: block;
	background: url('../images/icons.svg#icon-office365') no-repeat;
	width: 128px;
	height: 64px;
}
```
**Allow Subset and reduce download time**
All svg icons use currently 217kb. Well they size can be reduced by simple remove sections of the svg file. I makes it pretty handy because all icons are stored in just a single file. More icons are more complex than others. For example the Office 365 logo will be drawn more complex and therefore use more space. If gzip compression is activated on the server the file size will be reduced to 53kb.
So it won't use more than a regualar image. The fact that all is stored in a simple text file gives a lot of benefit of this kind of compressen.

**Reduce HTTP Request**
Icon font use one http request. SVG icons use just one http request. So there is nothing to do on this side.

** Custom colors **
The easiest way to apply custom colors is to embed it like an images:
```
        <svg class="icon2">
            <use xlink:href="images/icons.svg#icon-office365" />
        </svg>
```

In this case you can apply a custom color easy in css:
```
.icon2{
	fill: yellow;
	&:hover{
		fill: red;
	}
}
```
Since the SVG is not part of the DOM document you cannot pass custom colors to it. You can if the svg will be served together with the HTML. (Will reduce a HTTP Request). This will slow down the loading process.
What can be done in the SVG file is to have the same icon and pass in different color. In this case this needs to be done directly in the SVG file.

Another posibility is to use a mask-image and defile the color via background-color but this is definitly something for the future because IE doesn't support it at all. The other browser still have some issues with this.

To be honest while writing this comment. I started to doubt if it somehting the framework should consider now since the technological limitations seem way to hard for a regular developer to get it done without specific web development skill.
Maybe there are some gulp plugins out there that helps to get things done faster or better. What might can be done is to add it as an optional part. Maybe document how to use svg icons and last but not least why they should be considered. Similar to what I've written here.

**Comment by mikewheaton** [comment]
We discussed this today and while we think there are a lot of merits to SVGs, we're just not seeing enough issues with our web font to justify the development expense and the extra work this would put on those using Fabric.

It's a huge benefit that our icon font can inherit the font size and color of it's parent, and that our existing color and size classes can be used to override that. So we're sticking with the icon font for now.

Thanks everyone for the discussion and ideas! We'll continue to put stuff like this up on GitHub to look for feedback from the community.
