### ISSUE TITLE
Recommended style loading order

### ISSUE THREAD

**Issue by TheTedAdams** [OfficeDev/Office-UI-Fabric#401]
When trying to make a cancel/delete style button I wanted to set the button's bgColor to red.

I attempted to do this with the `.ms-bgColor-red` class, but because `fabric.components.min.css` was loaded *after* `fabric.min.css` (per recommendation in the [Getting Started Guide](http://dev.office.com/fabric/getting-started)), even though I specified the `ms-bgColor-red` class after the `.ms-Button` class, the `.ms-Button` class had higher specificity.

If I swap the loading order of the scripts (components and then core) it gives the core utility functions higher specificity so that they can override component defaults, which seems preferable to me.

Are there any reasons *not* to load the files in this reversed order? If not, then I might suggest swapping the order in the getting started guide, as it seems the expected behavior would be for `.ms-bgColor-red` (and other utility classes) to be able to override `.ms-Button` (and other component classes) defaults.

**Comment by mikewheaton** [comment]
Fabric implements the Office Design Language, which specifies all of the styles that are valid for a given component. So generally speaking we don't want to encourage developers to override the components' styles. In the case of Button, it only comes in gray (default) and blue (primary).

We've had similar questions like this (see #389) where we have to decide whether we'll make it easier for developers to deviate from the standard patterns or if we want to enforce those. I'm going to mark this as 'needs-discussion' so that we can make a decision.

For now, I'm not aware of any problems that would come from loading `fabric.components.min.css` before `fabric.min.css`, which will make the background color class work for you as you've discovered. You could also create an override class, as in [this CodePen](http://codepen.io/mikewheaton/pen/ONPjqQ)).

**Comment by TheTedAdams** [comment]
@mikewheaton thanks for the explanation about not necessarily wanting to support deviation from the design language. That makes sense, and I appreciate you being willing to discuss it.

I definitely know I can write my own class to override, but unless I'm bringing in the fabric source as a sub-module that means if Fabric ever changes their color value I'd have to duplicate any updates, which I'd like to avoid.

In my mind the utility classes would be useful as a means to override default styles while still using the fabric typography/color palette. At least that's how I use them. If I left everything default I would never need `ms-bgColor`, `ms-fontColor`, `ms-borderColor`, `ms-fontSize` etc.

**Comment by mikewheaton** [comment]
Thanks for your patience here, @TheTedAdams. We discussed this today and decided to stick with the current recommended loading order (`fabric.css` before `fabric.components.css`). The Fabric style classes, such as text or background color, are intended to be applied to the content within an app and not on top of the components' styles. We want to encourage developers to stick to the design language. Of course you're always free to write CSS override classes, we just don't want to go out of our way to support deviating from the design language.
