### ISSUE TITLE
Incorrect HTML in List samples

### ISSUE THREAD

**Issue by elegault** [OfficeDev/Office-UI-Fabric#436]
On http://dev.office.com/fabric/components/list:

The first HTML sample is missing the containing `<ul class="ms-List">` element, while the second is missing `<ul class="ms-List ms-List--grid">`

**Comment by mikewheaton** [comment]
I think this is actually another bug in our docs site, where when a component has multiple variants our HTML sample view concatenates all of the source together:

![image](https://cloud.githubusercontent.com/assets/1382445/13873557/90eb6296-ecf2-11e5-91a3-7a8870db00f5.png)

This will be fixed in our upcoming documentation rewrite. I've confirmed that the rendered samples have both `<ul class="ms-List">` and `<ul class="ms-List--grid">` respectively.
