### ISSUE TITLE
Use font-weight to determine the web font to use

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#442]
Hi,

just spot that the [@fontface](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/sass/_Fabric.Typography.Fonts.scss) definition is incorrect. All font declarations use the same font-weight but different font names. It is working but has a lot of negative side effects.

To be more specific the current font definition looks like this.
```
@font-face {
    font-family: "#{$ms-light} #{$ms-font-language}";
    src: local("Segoe UI Light"),
         url('#{$ms-font-directory}/#{$ms-font-path}/SegoeUI-Light.woff2') format('woff2'),
         url('#{$ms-font-directory}/#{$ms-font-path}/SegoeUI-Light.woff') format('woff'),
         url('#{$ms-font-directory}/#{$ms-font-path}/SegoeUI-Light.ttf') format('truetype');
    font-weight: normal;
    font-style: normal;
  }
```

instead the font face definition should look like.

```
@font-face {
    font-family: "#{$ms-font} #{$ms-font-language}";
    src: local("Segoe UI"),
         url('#{$ms-font-directory}/#{$ms-font-path}/SegoeUI-Light.woff2') format('woff2'),
         url('#{$ms-font-directory}/#{$ms-font-path}/SegoeUI-Light.woff') format('woff'),
         url('#{$ms-font-directory}/#{$ms-font-path}/SegoeUI-Light.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
  }
```

The $ms-light is not needed but instead I would recommend to use $ms-font. In addition for the light font the font-weight should be set to 300.

The following values are defined for the default font weights:
**100**    Thin (Hairline)
**200**    Extra Light (Ultra Light)
**300**    Light
**400**    Normal
**500**    Medium
**600**    Semi Bold (Demi Bold)
**700**    Bold
**800**    Extra Bold (Ultra Bold)
**900**    Black (Heavy)

This makes year css more cleaner and gives the browser the possibility to choose the correct font file. It also make the CSS file a little bit smaller.

**Comment by mikewheaton** [comment]
Excellent points, Stefan. This could also simplify localization. Right now we override the `font-family` of every class that uses that uses that font weight. This is repeated for every language. For example:

```
*[lang='vi-VN'] .ms-font-mi,
*[lang='vi-VN'] .ms-fontWeight-semibold,
*[lang='vi-VN'] .ms-fontWeight-semibold-hover:hover {
  font-family: 'Segoe UI Semibold Vietnamese', 'Segoe UI Semibold WestEuropean', 'Segoe UI Semibold', 'Segoe UI', Tahoma, Arial, sans-serif;
}
```

This means that all components must use Fabric classes (`<span class="ms-Thing-text ms-fontWeight-semibold">some text</span>`) or we have add a new override for every element that changes the font weight (adding `*[lang='vi-VN'] .ms-Thing-text` to the selector above). That would add a ton of bloat and be a nightmare to maintain.

With this method we wouldn't need to keep track of which classes use which font weights, as we can use `font-weight` directly rather than centralizing the overrides:

```
.ms-font-mi {
  font-weight: 600;
}
.ms-Thing-text {
  font-weight: 600;
}
```

It's also a potential fix for #443.

**Comment by StfBauer** [comment]
True will help you with languages too. Instead of referencing different font names you can simply use throughout the css just the default font-weight.
Just in case the browser cannot find the exact font file, the font will be replaced with the next matching font. I guess it will be great enhancement and overall the font handling will be more fail safe.

**Comment by mikewheaton** [comment]
We're now using `font-family` to set a single font family at the base of every component, and `font-weight` to change the weight.
