### ISSUE TITLE
Documentation: Icon link does not scroll to icons section

### ISSUE THREAD

**Issue by knutkj** [OfficeDev/Office-UI-Fabric#475]
Icon link does not scroll down to icons on dev.office.com:

http://dev.office.com/fabric/styles#icons

**Comment by av-virlan** [comment]
It seems to happen because of class <b>.docs-colorContainer</b> which has a <b>float:left</b> style. As soon as that's removed it looks good

Before:
![floating container](https://cloud.githubusercontent.com/assets/5521715/14232079/b2039da4-f9a4-11e5-9fee-789ee8e26bea.png)

After:
![no float container](https://cloud.githubusercontent.com/assets/5521715/14232080/b6e07554-f9a4-11e5-819c-bda27b7e3497.png)

**Comment by mikewheaton** [comment]
Thanks @knutkj for reporting this and @av-virlan for the possible fix. We'll look into this.

**Comment by mikewheaton** [comment]
This issue has been fixed and will be included when we next update the documentation site.
