### ISSUE TITLE
Documentation: Variants use the same template and samples contain duplicate templates

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/Office-UI-Fabric#522]
The button implementation in the documentation is somehow not correct.
http://dev.office.com/fabric/components/button

The button includes the icon but the icon won't be show. Maybe you remove the icon inside the button or show the icon on the button.

The plus sign is not required to create a basic button I think.

**Comment by mikewheaton** [comment]
There are a couple issues here that we need to fix:

1. We have a bug in our samples where each sample contains the HTML of all the previous samples. So if you look at the HTML for the 'Command and Compound Buttons' sample, you'll see the default and primary buttons in there as well. Very confusing.
2. We're using the same HTML source for all button types. This is the issue you're seeing where a standard button contains `ms-Button-icon` and `ms-Button-description`, when neither of those would be displayed in a standard button. It works but it's confusing.

The first issue is a bug in our documentation site generator.

We're doing a rewrite of the components using Handlebars templates. This will still render out to HTML, but it will be smart enough to exclude elements that aren't in use by a particular variant. So that will fix the second issue.

**Comment by mikewheaton** [comment]
Both of these issues are fixed in the new changes for Fabric 3.0. 😄
