### ISSUE TITLE
Replace LESS with Sass

### ISSUE THREAD

**Issue by SandHilt** [OfficeDev/Office-UI-Fabric#56]

**Comment by donatj** [comment]
:+1:

**Comment by andrewconnell** [comment]
:+1: :+1:

**Comment by una** [comment]
:+1: :+1: :+1:

**Comment by pascalberger** [comment]
+1

**Comment by Diablo-D3** [comment]
:+1:

**Comment by CuddleBunny** [comment]
I personally prefer LESS, perhaps maintaining both wouldn't be out of the question.

**Comment by Jahnp** [comment]
This would be a pretty big change, but we do see the value in supporting SASS/SCSS in some way. We aren't in a position to fully replat our styles any time soon, but like @CuddleBunny mentions, I could see spinning up parallel versions at some point.

Tidbit for the sake of curiosity: we originally started with LESS because it had pretty broad adoption across product teams at Microsoft.

**Comment by mrmckeb** [comment]
Agreed. Less is no longer the standard, as Sass has gotten much larger traction and a bigger following.

**Comment by tidg** [comment]
👍 +1 👍

**Comment by matthew-dean** [comment]
They're used by different groups for different reasons.

LESS is easier to learn as its a intentionally tight feature set to cover the vast majority of use cases, but not all.

Like CSS, LESS is declarative. SASS is imperative. So that also makes it a more familiar concept to web developers. For instance, LESS had concepts like block scoping and cascading values that SASS does not have. So it's more like CSS+ and SASS is more like PHP or Ruby with CSS-like syntax.

So LESS doesn't try to be the standard but a solution to a different set of problems as priority. We (core Less users) regularly suggest Sass when people need a more programming-language-like imperative construct. Basically, Less is the iPod and Sass is the Zune, so, yup, Sass has way more features. :-) 

Use what suits your project!

**Comment by andrewconnell** [comment]
@matthew-dean by comparing SASS to Zune you have just made enemies with web developers at large! :smiley:

**Comment by matthew-dean** [comment]
@andrewconnell lol a low blow, I know. But sometimes I hear "Sass is better than Less because it has more features." Which is pretty much exactly the same as saying, "Zune is better than the iPod because it has more features." Fewer features sometimes makes for faster adoption, less confusion, and easier onboarding for new devs, so that's the reason I bring up the comparison.

**Comment by SandHilt** [comment]
Look this : https://css-tricks.com/sass-vs-less/

**Comment by StfBauer** [comment]
I think many web developer switched from LESS to SASS. Support both will be a good option for those you still use less.

**Comment by timschoch** [comment]
+1

**Comment by matthew-dean** [comment]
I mentioned this thread in this post, if you're curious: http://getcrunch.co/2015/10/08/less-the-worlds-most-misunderstood-css-pre-processor/

**Comment by ericthompson** [comment]
Hi all! Looping back here to mention to everyone that our latest version, [1.2.0](https://github.com/OfficeDev/Office-UI-Fabric/releases/tag/1.2.0), includes the beginnings of our conversion to SASS - check it out! We've still got work to do, but we're open to hearing opinions/feedback.

**Comment by andrewconnell** [comment]
Awesome update! How soon can we expect to this to be in the CDN?

**Comment by andrewconnell** [comment]
Reason I ask – next week we will have our first release of the Angular Directives for Office UI Fabric and our demos reference the CDN links… we’d love to point to the latest stuff…

**Comment by SharePointOscar** [comment]
Oh nice now we're really up to par with Bootstrap, since it has AngularJS directives as well.

Stoked, can't wait to integrate them into my boilerplate MEANS open source project http://github.com/SharePointOscar/MEANS


Sent from my 6S

On Jan 8, 2016, at 11:43 AM, Andrew Connell <notifications@github.com<mailto:notifications@github.com>> wrote:

Reason I ask - next week we will have our first release of the Angular Directives for Office UI Fabric and our demos reference the CDN links... we'd love to point to the latest stuff...

-

**Comment by ericthompson** [comment]
@andrewconnell - we're currently pushing to get our CDN updated asap. I don't have a timeframe yet, but we're hoping for the next week or 2.

**Comment by andrewconnell** [comment]
@SharePointOscar just FYI... we shipped the first drop of http://ngofficeuifabric.com, Angular directives for Office UI Fabric

**Comment by SharePointOscar** [comment]
Yummy!  Time to start integrating them into my MEANS boilerplate project!  Thanks for the heads up AC!

From: Andrew Connell
Reply-To: OfficeDev/Office-UI-Fabric
Date: Friday, January 15, 2016 at 10:39 AM
To: OfficeDev/Office-UI-Fabric
Cc: Oscar Medina
Subject: Re: [Office-UI-Fabric] Transform styles LESS to SASS (#56)


@SharePointOscar<https://github.com/SharePointOscar> just FYI... we shipped the first drop of http://ngofficeuifabric.com, Angular directives for Office UI Fabric

**Comment by andrewconnell** [comment]
Np… planning another drop sometime early next week with at least one more directive…

**Comment by mikewheaton** [comment]
Replacing LESS with Sass is underway, see pull request #279. We plan to have LESS completely removed when we release Fabric 2.0.

**Comment by StfBauer** [comment]
:+1:

**Comment by mikewheaton** [comment]
Finished in #303!

**Comment by purtuga** [comment]
Sad to learn that LESS is removed and no longer supported...  :disappointed:
Supporting SASS, although may provide you a richer set of features - that you may or may not use - it does add complexity and intimidation around setting up an environment for anyone that may want to use this project to create mashups.  It also limits us LESS users in actually taking advantage of Office UI Fabric... In my personal use cases, I have not been able to find a gap in functionality that required me to go use SASS - perhaps you guys have and thus the change in tooling...  

That being said, I will eventually move to use SASS, since it seems that tool is moving quickly into becoming the most popular one.. and thus the one with best support.So I'm not a hatter of the tool... but I'm not ready yet either... so with that:

___

## How to use Last release with LESS Support

For anyone that may find this thread and still want to use the LESS source, there is what I did:

The instruction below are for v1.2.1 - which seems to be the last [tagged](https://github.com/OfficeDev/Office-UI-Fabric/tags) version that had LESS support. 

From the command prompt:

```
$ git fetch --tags
$ git checkout -b release_1-2-1 1.2.1
```

If using Bower, just run this command instead of the default approach:

```
 bower install --save-dev OfficeDev/Office-UI-Fabric#1.2.1
```

___

now... back to using Office UI Fabric on custom widgets.... :grin: 

/Paul

**Comment by matthew-dean** [comment]
> since it seems that tool is moving quickly into becoming the most popular one

Sorry, but under what metric have people determined that Sass is more popular than Less?

https://twitter.com/matthewdeaners/status/693228336814817280

**Comment by mikewheaton** [comment]
We understand that this isn't a welcome change for everyone. We've communicated that it's coming (in this issue, our [prior release notes](https://github.com/OfficeDev/Office-UI-Fabric/releases/tag/1.2.0), and in [our roadmap](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/ghdocs/ROADMAP.md)) but we know it will be a surprise to some.

For us it's not a question of the features of LESS vs Sass or the wider popularity or trendiness of either one – what we've heard from our users, both inside and outside of Microsoft, is that Sass is preferred. We considered supporting both but this would burden our development process and keep us from fixing bugs and developing features. As a small team we have to be careful about where we spend our time. Thanks for your understanding.

**Comment by matthew-dean** [comment]
> For us it's not a question of the features of LESS vs Sass or the wider popularity or trendiness of either one – what we've heard from our users, both inside and outside of Microsoft, is that Sass is preferred. 

That's a good answer, and makes sense.

**Comment by purtuga** [comment]
Hi @matthew-dean... You are right: I don't have a metric I can point you to... its simply my personal opinion based on my recent encounters. I'm a LESS user and I have been feeling as if perhaps its time for me to move on from it... Several of the libraries/widgets I have used recently all had their CSS written in SASS... 

@mikewheaton Thank you for our response. I understand the motive and agree with @matthew-dean : its ultimately what makes more sense for this project and the majority of its users.
