### ISSUE TITLE
MessageBar specific classes are missing in fabric.components.css 2.6.0

### ISSUE THREAD

**Issue by andikrueger** [OfficeDev/Office-UI-Fabric#596]
Building the current project results in css files without the messagebar component.

**Comment by mikewheaton** [comment]
Thanks for reporting this issue and tracking down the root cause, @andikrueger. I'll get started on a 2.6.1 patch release to fix it.

We've run into this same problem in the past; it's frustrating that we let such glaring problems get through the release process. In Fabric 3.0 and later we'll be using the main `fabric.components.css` stylesheet on the component sample pages (rather than individual `MessageBar.css`-type files) so that we can catch these issues. We'll be testing those sample pages and requiring full documentation before merging anything in.
