### ISSUE TITLE
datepicker markup too complex

### ISSUE THREAD

**Issue by kennywangjin** [OfficeDev/Office-UI-Fabric#71]
to show a datepicker to a user, there are too many lines markup code.
is that possible to generate these markups via javascript, just like jquery ui datepicker do:
// input type='date'
//
//$('input[type="date"]').datepicker({});
//
this seems more convenient to use......

**Comment by CuddleBunny** [comment]
+1

**Comment by battletoilet** [comment]
We will definitely take a look at that. Thanks for your input.

**Comment by wdo3650** [comment]
A simplified DatePicker is in the develop branch #115 .  Thanks for your input @kennywangjin.

**Comment by wdo3650** [comment]
After discussing this component both internally and with the community, we believe it makes more sense to remove the jQuery-generated markup from DatePicker, since Fabric is more focused on the styling of components independent of its JS implementation. This puts the markup straight in the DOM, as it was before, allowing easier access to the elements, attributes and css without the need for Javascript to accomplish everyday tasks. 

Thank you for the feedback. It prompted a great discussion internally about about what Fabric should focus on.
