### ISSUE TITLE
Segoe UI Regular EastEuropean, in 2015?

### ISSUE THREAD

**Issue by Kwpolska** [OfficeDev/Office-UI-Fabric#76]
Why does a font named *Segoe UI Regular EastEuropean* exist in 2015? I thought we are all embracing Unicode out there…

**Comment by notandrew** [comment]
This font exists for a couple of reasons:
1) It's the font that Microsoft uses for 'East European' text (not only used in Fabric.)  We also have subsets for Vietnamese, Thai, Cyrillic, etc.
2) It exists for keeping font downloads small.  We could create one giant font which has all the smaller subsets included, but the time it takes for the font download would be noticeable.

The way many products/websites work at Microsoft is to identify the users' language and then supply the localized text with the correct font and font stack. 

If one were to use the Segoe UI Regular West European font to show a character specific to the East European character set, the resulting character may be shown in a fallback font rather than in a Segoe variant.  
Hope this helps.
