### ISSUE TITLE
CSS Capitalization Conventions

### ISSUE THREAD

**Issue by CuddleBunny** [OfficeDev/Office-UI-Fabric#78]
There seems to be quite a bit of seemingly random capitalization of CSS classes within the samples. 

The pattern that seems to be present is something like:
  - Prefix with `ms-`
  - Components are PascalCase (`DatePicker`)
  - Properties (`ms-TextField-field`), Constants (`ms-fontColor-white`), and Sub-Components (`ms-Icon--chevronRight`) are camelCase.

Should these be made all lower case to conform with other similar web libraries? Or is there some precedent within other Office code that may be more important to conform to?

**Comment by Jahnp** [comment]
Very keen eye :) Our conventions actually follow very similar patterns to those in [SUIT CSS](https://github.com/suitcss/suit/blob/master/doc/naming-conventions.md), with some of the more information-dense "core" classes (e.g. `ms-fontColor-white`) being the sole intentional deviations (since they are very utility-like). We should probably publish those conventions so folks know what to snap to when contributing.

We chose SUIT's conventions for its scalable, namespaced, component-oriented approach--it lends itself very well to large projects and toolkits. It's also being used by several other MS web products (partially because of Fabric)--you'll notice OneDrive follows it as well.

**Comment by CuddleBunny** [comment]
Good answer. I've never seen SUIT CSS and have never thought of CSS as particularly scalable in the first place. This makes much more sense now.

**Comment by LezaMax** [comment]
Seems this issue is closed now. Thanks @Jahnp for the details.
